// my-react-app/src/components/About.js
import React from 'react';
import {
    useHistory,
    useLocation,
    useParams
} from "react-router-dom";

class AboutInternalComponent extends React.Component {

    componentDidMount() {

        console.log('About componentDidMount');

    }

    componentWillUnmount() {

        console.log('About componentWillUnmount');

    }

    render() {

        return (
            <div>
                <p>This is some really nice About page.<br />
                    We got param from URL /about/:superduperparam - {this.props.superduperparam}<br />
                    We got query string someneatquerystring - {this.props.someneatquerystring}</p>
                <p>Buwahahaha, and another normally passed<br />this.props.someprop: {this.props.someprop}</p>
            </div>
        );

    }

}

function useQuery() {
    return new URLSearchParams(useLocation().search);
}

function About(props) {

    let history = useHistory();
    let location = useLocation();

    let params = useParams();
    //let superduperparam = params.superduperparam;
    let { superduperparam } = useParams();

    let query = useQuery();
    let someneatquerystring = query.get('someneatquerystring');

    console.log('history in About', history);
    console.log('location in About', location);
    console.log('params in About', params);

    /* hmm, useParams doesn't work with this
    return class extends React.Component {

        render() {

            return (
                <div>
                    <p>This is some really nice About page. We got superduperparam: {superduperparam}</p>
                    <p>Buwahahaha</p>
                </div>
            );

        }

    };
    */

    return (
        <AboutInternalComponent
            superduperparam={superduperparam}
            someneatquerystring={someneatquerystring}
            someprop={props.someprop}>
            {/* Passing useParams to internally defined class */}
        </AboutInternalComponent>
    );

}

export default About;

// my-angular-app/src/app/components/about/about.component.ts
import {
  Component,
  Input,
  OnInit,
  OnDestroy
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit, OnDestroy {

  @Input() someprop;

  superduperparam = null;

  private routeParamUpdate: Subscription;

  // RouteParams ROUTER_PROVIDERS
  constructor(private route: ActivatedRoute, private router: Router) {

    // data passed from route
    // https://yakovfain.com/2015/11/11/angular-2-passing-data-to-routes/
    console.log('---', route);
    console.log('---', route.snapshot);

  }

  ngOnInit() {

    console.log('About ngOnInit');

    // @Input... need to think of better way
    this.someprop = this.route.snapshot.data.someprop;

    // refresh when route params change
    // https://medium.com/@mvivek3112/reloading-components-when-change-in-route-params-angular-deed6107c6bb
    // https://stackoverflow.com/questions/53680613/reload-component-when-change-parts-routing-in-angular
    this.routeParamUpdate = this.route.params.subscribe(params => {

      this.superduperparam = this.route.snapshot.paramMap.get('superduperparam');

    });

  }

  ngOnDestroy() {

    console.log('About ngOnDestroy');

    this.routeParamUpdate.unsubscribe();

  }

}

<div>
    <p>This is some really nice About page.<br />
        We got param from URL /about/:superduperparam - {{superduperparam}}<br />
        We got query string someneatquerystring - {{someneatquerystring}}</p>
    <p>Buwahahaha, and another normally passed<br />@Input someprop: {{someprop}}</p>
</div>
