// my-react-app/src/App.js
import React from 'react';
import {
  BrowserRouter,
  HashRouter,
  Switch,
  Route,
  Link
} from "react-router-dom";
import logo from './logo.svg';
import './App.css';
import RandomCoolComponent from './components/RandomCoolComponent';
import ReallyAwesomeForm from './components/ReallyAwesomeForm';
import About from './components/About';
import blah from './models/BlahModel';

function NoMatch404(props) {

  return (
    <div>404 no matching URL</div>
  );

}

function App(props) {

  function buttonGotClicked(date, numClicks) {

    console.log('buttonGotClicked on App.js:', date);

    blah.text = 'I got changed by App.js. Num clicked: ' + numClicks;

    alert('Date is:' + date);

  }

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.<br />
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        {/*
        <HashRouter> - like angularjs, appends hash # in URL.
        or
        <BrowserRouter basename="/path/to/here">
        - basename - used by react router during client side routing
        - "homepage" set in package.json - used by build process so generated HTML file can refer to stuff to include
          - example: "homepage": "/path/to/here"
        https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing
        https://muffinman.io/react-router-subfolder-on-server/
        */}
        <BrowserRouter basename="/react">
          <div className="mainContainer">
            <nav className="navContainer">
              <ul className="nav flex-column">
                <li className="nav-item">
                  <Link className="nav-link"
                    to="/">Home</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link"
                    to="/form">Fill in some form</Link>
                </li>
                {/*
                <li className="nav-item">
                  <Link className="nav-link"
                    to="/do/api">Make some API call</Link>
                </li>
                */}
                <li className="nav-item">
                  {/*
                  <Link className="nav-link"
                    to={'/about/' + blah.foobar}>About</Link>
                  */}
                  <Link className="nav-link"
                    to={{
                      pathname: '/about/' + blah.foobar,
                      state: {
                        someUserDefined: 'Custom data that entered as state object: ' + blah.foobar
                      }
                    }}>About</Link>
                </li>
              </ul>
            </nav>
            <div className="contentContainer">
              <Switch className="wow">
                <Route path="/" exact>
                  <RandomCoolComponent blah={blah}
                    onRandomButtonClick={(date, numClicks) => buttonGotClicked(date, numClicks)} />
                </Route>
                <Route path="/form">
                  <ReallyAwesomeForm />
                </Route>
                <Route path="/about/:superduperparam">
                  <About someprop={'Hello world'} />
                </Route>
                {/*
                fallback 404 page
                https://tylermcginnis.com/react-router-handling-404-pages/
                */}
                <Route component={NoMatch404} />
              </Switch>
            </div>
          </div>
        </BrowserRouter>
      </header>
    </div>
  );
}

export default App;

// my-angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { RandomCoolComponent } from './components/random-cool.component';
import { Subscription } from 'rxjs';
import blah from './models/blah.model';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {

    constructor() {

        this.blah = blah;

    }

    blah = null;

    private randomCoolComponentButtonClick: Subscription

    onActivate(activatedComponent) {

        console.log('onActivate:', activatedComponent);

        if (activatedComponent instanceof RandomCoolComponent) {

            // https://angular.io/api/core/EventEmitter#subscribe
            // https://medium.com/@sujeeshdl/angular-parent-to-child-and-child-to-parent-communication-from-router-outlet-868b39d1ca89
            // https://stackoverflow.com/questions/36494509/how-to-unsubscribe-from-eventemitter-in-angular-2
            let asdf: RandomCoolComponent = activatedComponent as RandomCoolComponent;
            this.randomCoolComponentButtonClick = asdf.onRandomButtonClick.subscribe((data) => {
                this.buttonGotClicked(data.date, data.numClicks);
            });

        }

    }

    onDeactivate(deactivatedComponent) {

        console.log('onDeactivate:', deactivatedComponent);

        if (deactivatedComponent instanceof RandomCoolComponent) {

            let asdf: RandomCoolComponent = deactivatedComponent as RandomCoolComponent;
            this.randomCoolComponentButtonClick.unsubscribe();

        }

    }

    buttonGotClicked(date, numClicks) {

        console.log('buttonGotClicked on App.js:', date);

        this.blah.text = 'I got changed by App.js. Num clicked: ' + numClicks;

        alert('Date is:' + date);

    }

}

<div class="App">
  <header class="App-header">
    <div class="mainContainer">
      <nav class="navContainer">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" routerLink="/" routerLinkActive="active">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/" routerLinkActive="active">Fill in some form</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/about/wooooot" routerLinkActive="active">About</a>
          </li>
        </ul>
      </nav>
      <div class="contentContainer">
        <router-outlet (activate)="onActivate($event)" (deactivate)="onDeactivate($event)"></router-outlet>
        <random-cool-component [blah]="blah" (onRandomButtonClick)="buttonGotClicked($event)"></random-cool-component>
      </div>
    </div>
    <!--
    <BrowserRouter basename="/react">
      <div className="mainContainer">
        <nav className="navContainer">
          <ul className="nav flex-column">
            <li className="nav-item">
              <Link className="nav-link" to="/">Home</Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/">Fill in some form</Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to={{
                      pathname: '/about/' + props.blah.foobar,
                      state: {
                        someUserDefined: 'Custom data that entered as state object: ' + props.blah.foobar
                      }
                    }}>About</Link>
            </li>
          </ul>
        </nav>
        <div className="contentContainer">
          <Switch className="wow">
            <Route path="/" exact>
              <RandomCoolComponent blah={props.blah} onRandomButtonClick={(date, numClicks)=> buttonGotClicked(date,
                numClicks)} />
            </Route>
            <Route path="/about/:superduperparam">
              <About someprop={'Hello world'} />
            </Route>
            <Route component={NoMatch404} />
          </Switch>
        </div>
      </div>
    </BrowserRouter>
    -->
  </header>
</div>
