// my-react-app/src/components/RandomCoolComponent.js
import React from 'react';
import SomeNeatNumberList from './SomeNeatNumberList';

var someVariable = 0;

const someNeatData = [
    {
        id: 1,
        name: 'one'
    },
    {
        id: 2,
        name: 'two'
    },
    {
        id: 3,
        name: 'three'
    }
];

class RandomCoolComponent extends React.Component {

    constructor(props) {

        super(props);

        this.state = {
            date: new Date()
        };

    }

    tick() {

        /*
        this.setState(function (state, props) {

            return {
                date: new Date()
            };

        });
        */

        this.setState((state, props) => ({
            date: new Date()
        }));

    }

    componentDidMount() {

        // https://reactjs.org/docs/state-and-lifecycle.html
        this.timerID = setInterval(
            () => this.tick(),
            1000
        );

    }

    componentWillUnmount() {

        clearInterval(this.timerID);

    }

    onButtonClick(e, msg) {

        console.log(msg);
        console.log('Time is:', this.state.date);

        someVariable++;

        // Send data back up to parent via method defined by this.props
        // https://reactjs.org/docs/lifting-state-up.html
        this.props.onRandomButtonClick(this.state.date, someVariable);

    }

    render() {

        return (
            <div>
                <p>Current time is: {this.state.date.toLocaleTimeString()}</p>
                <p>Some variable within RandomCoolComponent: {someVariable} </p>
                <p>Here is props.blah.text: {this.props.blah.text}</p>
                <button type="button"
                className="btn btn-success"
                onClick={(e) => this.onButtonClick.call(this, e, 'I got clicked')}>What time is it?</button>
                {/* Passing children */}
                <SomeNeatNumberList numbers={someNeatData}>
                    <h3>This is some numbers list</h3>
                    <span>fancy list, yo</span>
                </SomeNeatNumberList>
            </div>
        );

    }

}

export default RandomCoolComponent;

// my-angular-app/src/app/components/random-cool.component.ts
import {
    Component,
    OnInit,
    OnDestroy,
    Input,
    Output,
    EventEmitter,
    ViewChildren,
    QueryList
} from '@angular/core';
import { SomeNeatNumberList } from './some-neat-number-list.component';
import { ActivatedRoute } from '@angular/router';

@Component({
    selector: 'random-cool-component',
    templateUrl: './random-cool.component.html'
    //styleUrls: ''
})
export class RandomCoolComponent implements OnInit, OnDestroy {

    // https://angular.io/guide/component-interaction#pass-data-from-parent-to-child-with-input-binding
    @Input() blah;

    // https://angular.io/guide/component-interaction#parent-listens-for-child-event
    //@Outut() onRandomButtonClick = new EventEmitter<{date, numClicks}}>();
    //@Output() onRandomButtonClick = new EventEmitter<{ date: Date, numClicks: Number }>();
    @Output() onRandomButtonClick = new EventEmitter<{ date: Date, numClicks: Number }>();

    // https://netbasal.com/understanding-viewchildren-contentchildren-and-querylist-in-angular-896b0c689f6e
    @ViewChildren('MyParagraph') paragraph_elements!: QueryList<any>;
    @ViewChildren(SomeNeatNumberList) numbersList!: QueryList<any>;

    date = null;
    someVariable = 0;

    private timerID = null;

    readonly someNeatData = [
        {
            id: 1,
            name: 'one'
        },
        {
            id: 2,
            name: 'two'
        },
        {
            id: 3,
            name: 'three'
        }
    ];

    constructor(private route: ActivatedRoute) {

        // data passed from route
        // https://yakovfain.com/2015/11/11/angular-2-passing-data-to-routes/
        console.log('---', route);
        console.log('---', route.snapshot);

        this.date = new Date();

    }

    tick() {

        this.date = new Date();

    }

    // https://angular.io/guide/lifecycle-hooks
    ngOnInit() {

        console.log('ngOnInit');

        // @Input... need to think of better way
        this.blah = this.route.snapshot.data.blah;

        this.timerID = setInterval(
            () => this.tick(),
            1000
        );

    }

    ngOnDestroy() {

        console.log('ngOnDestroy');

        clearInterval(this.timerID);

    }

    onButtonClick(e, msg) {

        console.log(e);
        console.log('msg:', msg);
        console.log('Time is:', this.date);

        console.log(this.paragraph_elements);
        this.paragraph_elements.forEach(element => console.log(element));
        console.log(this.numbersList);
        this.numbersList.forEach(element => console.log(element));

        this.someVariable++;

        // Send data back up to parent via method defined by this.props
        // https://reactjs.org/docs/lifting-state-up.html
        this.onRandomButtonClick.emit({
            date: this.date,
            numClicks: this.someVariable
        });

    }

}
<div>
	<p #MyParagraph>Current time is: {{date.toLocaleTimeString()}}</p>
	<p #MyParagraph>Some variable within RandomCoolComponent: {{someVariable}} </p>
	<p>Here is blah.text: {{blah.text}}</p>
	<button type="button" class="btn btn-success" (click)="buttonGotClicked($event, 'I got clicked')">What time is it?</button>
	<some-neat-number-list [numbers]="someNeatData">
		<h3>This is some numbers list</h3>
		<span>fancy list, yo</span>
	</some-neat-number-list>
	<!--
	<p>Current time is: {this.state.date.toLocaleTimeString()}</p>
	<p>Some variable within RandomCoolComponent: {someVariable} </p>
	<p>Here is props.blah.text: {this.props.blah.text}</p>
	<button type="button" className="btn btn-success" onClick={(e)=> this.onButtonClick.call(this, e, 'I got
		clicked')}>What time is it?</button>
		<SomeNeatNumberList numbers={someNeatData}>
			<h3>This is some numbers list</h3>
			<span>fancy list, yo</span>
		</SomeNeatNumberList>
	-->
</div>
